project:
  type: website
  output-dir: _site
  
filters:
  - cable-header.lua # Include the new Lua filter

website:
  title: "declassified"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cables/index.qmd
        text: Cables
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/CarwilB/declassified
          - text: Report Issue
            href: https://github.com/CarwilB/declassified/issues

collections:
  cables:
    directory: cables         # change to data/cables-usa-test-md if that's where your posts are
    sort: date asc            # oldest â†’ newest
    path: cables              # output URL prefix (/cables/...)

language:
  title-block-published: "Date"

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Courier+Prime:ital,wght@0,400;0,700;1,400&family=Special+Elite&display=swap" rel="stylesheet">

editor: visual

